### ISSUE TITLE
Unknown column 'u.authMethod' in 'field list'

### ISSUE THREAD

**Issue by ldn01** [biraj21/react_blogs#2]
running the services this error is thrown, I think the sql script needs updating:

  sqlMessage: "Unknown column 'u.authMethod' in 'field list'",
  sql: 'SELECT\n' +
    '        p.*,\n' +
    '        u.name userName,\n' +
    '        u.avatarPath userAvatarPath,\n' +
    '        u.authMethod userAuthMethod\n' +
    '      FROM Post p JOIN User u\n' +
    '      ON p.userId = u.id\n' +
    "      WHERE p.status = ? - parameters:['pub']",
  fatal: false,
  errno: 1054,
  sqlState: '42S22',
  code: 'ER_BAD_FIELD_ERROR'
}
SqlError: (conn=86, no: 1054, SQLState: 42S22) Unknown column 'u.authMethod' in 'field list'
sql: SELECT
        p.*,
        u.name userName,
        u.avatarPath userAvatarPath,
        u.authMethod userAuthMethod
      FROM Post p JOIN User u
      ON p.userId = u.id
      WHERE p.status = ? - parameters:['pub']

**Comment by ldn01** [comment]
this seemed to work for me... please let me know what u update from your side so I can check it's correct.

  `authMethod` enum('google','email') NOT NULL,

**Comment by biraj21** [comment]
thanks for pointing this out. the reason for this error is that the server/db.sql file that i've committed here is not the one that i have on my system. basically it's old and it doesn't have the required columns. i'll update it & let you know.
